swagger: '2.0'
info:
  version: "100500"
  title: KEK
  default: aaaaaaaaaaaaaaaaaaaaaaaa
  description: Click Terms of Service
  termsOfService: "javascript:alert(document.domain)"
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
